@startuml
(View stories) as (Stories)
(View story) as (Story)
(View page) as (Page)
(Choose option) as (Option)

User --> (Stories)
User --> (Option)
User --> (Story)
User --> (Page)
(Option) --> (Page)

@enduml
